---
- name: Configuration complete des serveurs web
  hosts: webservers
  become: yes
  
  vars:
    app_user: webapp
    app_dir: /opt/webapp
    nginx_worker_processes: auto
  
  pre_tasks:
    - name: Mise a jour du systeme
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600
  
  roles:
    - common
    #- nginx
    #- webapp
    #- monitoring
  
  post_tasks:
    - name: Verification finale des services
      service:
        name: "{{ item }}"
        state: started
      loop:
        - nginx
        - node_exporter
        - filebeat