---
- name: Configuration complète des serveurs web
  hosts: webservers
  become: yes
  
  vars:
    app_user: webapp
    app_dir: /opt/webapp
    nginx_worker_processes: auto
  
  pre_tasks:
    - name: Mise à jour du système
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600
  
  roles:
    - common
    - nginx
    - webapp
    - monitoring
  
  post_tasks:
    - name: Vérification finale des services
      service:
        name: "{{ item }}"
        state: started
      loop:
        - nginx
        - node_exporter
        - filebeat